name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.6.1
description: Plugin for the Total Freedom server.
author: StevenLawson / Madgeek1450
commands:
  cage:
    description: Superadmin command - Place a cage around someone.
    usage: /<command> <partialname> [off | outermaterial] [water | lava]
  cake:
    description: Superadmin command - For the people that are still alive.
    usage: /<command>
  clearall:
    description: Superadmin command - Removes all entities, nicks and disguises
    usage: /<command>
  cmdlist:
    description: Show all commands for all server plugins.
    usage: /<command>
  creative:
    description: Quickly change your own gamemode to creative, or define someone's username to change theirs.
    usage: /<command> [partialname]
  csay:
    description: Telnet command - Send a chat message with chat formatting over telnet.
    usage: /<command> [partialname]
  deop:
    description: Superadmin command - Deop a player
    usage: /<command> <playername>
  deopall:
    description: Superadmin command - Deop everyone on the server. Use 'purge' to clear ops.txt as well.
    usage: /<command> [purge]
  enchant:
    description: Enchant items.
    usage: /<command> <list | addall | reset | add <name> | remove <name>>
  expel:
    description: Superadmin command - Push people away from you.
    usage: /<command> [radius] [strength]
  explosives:
    description: Superadmin command - Enable/disable explosives and set effect radius.
    usage: /<command> <on | off> [radius]
  fireplace:
    description: Superadmin command - Enable/disable fire placement.
    usage: /<command> <on | off>
  firespread:
    description: Superadmin command - Enable/disable fire spread.
    usage: /<command> <on | off>
  flatlands:
    description: Goto the flatlands.
    usage: /<command>
  fluidspread:
    description: Superadmin command - Enable/disable fluid spread.
    usage: /<command> <on | off>
  fr:
    description: Superadmin command - Freeze players (toggles on and off).
    usage: /<command> [target | reset]
  fuckoff:
    description: You'll never even see it coming.
    usage: /<command>
  gadmin:
    description: Superadmin command - Use admin commands on someone by hash. Use mode 'list' to get a player's hash. Other modes are kick, nameban, ipban, ban, op, deop, ci
    usage: /<command> [list | [<kick | nameban | ipban | ban | op | deop | ci> <targethash>] ]
  gcmd:
    description: Superadmin command - Send a command as someone else.
    usage: /<command> <fromname> <outcommand>
  glist:
    description: Superadmin command - Ban/Unban any player, even those who are not logged in anymore.
    usage: /<command> <purge | <ban | unban> <username>>
  gtfo:
    description: Superadmin command - Makes someone GTFO (deop and ip ban by username).
    usage: /<command> <partialname>
  kicknoob:
    description: Superadmin command - Kick all non-superadmins on server.
    usage: /<command>
  landmine:
    description: Set a landmine trap.
    usage: /<command>
  lavadmg:
    description: Superadmin command - Enable/disable lava damage.
    usage: /<command> <on | off>
  lavaplace:
    description: Superadmin command - Enable/disable lava placement.
    usage: /<command> <on | off>
#  levelup:
#    description: Level up!
#    usage: /<command>
  list:
    description: Lists the real names of all online players.
    usage: /<command>
  moblimiter:
    description: Owner command - Controll mob rezzing parameters.
    usage: /<command> <on|off|setmax <count>|dragon|giant|ghast|slime>
  mp:
    description: Purge all mobs in all worlds.
    usage: /<command>
  mp44:
    description: Superadmin Command - Modern weaponry, FTW. Use 'draw' to start firing, 'sling' to stop firing.
    usage: /<command> <draw | sling>
  nether:
    description: Goto the nether.
    usage: /<command>
  nonuke:
    description: Superadmin command - Attempt to detect "invisible griefers" and "nukers".
    usage: /<command> <on | off> [range] [blockrate]
  op:
    description: Makes a player operator
    usage: /<command> <playername>
  opall:
    description: Superadmin command - Op everyone on the server, optionally change everyone's gamemode at the same time.
    usage: /<command> [-c | -s]
  ops:
    description: Superadmin command - Manage operators
    usage: /<command> [list | purge]
  opme:
    description: Superadmin command - Automatically ops user.
    usage: /<command>
  orbit:
    description: Superadmin command - POW!!! Right in the kisser! One of these days Alice, straight to the Moon!
    usage: /<command> <target> [power]
  prelog:
    description: Superadmin command - Enable/disable the command prelogger. When this is on, logs will be filled with many duplicate messages.
    usage: /<command> <on | off>
  qdeop:
    description: Quick De-Op - deop someone based on a partial name.
    usage: /<command> <partialname>
  qop:
    description: Quick Op - op someone based on a partial name.
    usage: /<command> <partialname>
  radar:
    description: Shows nearby people sorted by distance.
    usage: /<command> [range]
  rank:
    description: Shows your rank.
    usage: /<command>
  rawsay:
    description: Owner Command - Broadcasts the given message with no extra formatting.
    usage: /<command> <message>
  rd:
    description: Remove all projectiles, dropped items, experience orbs, primed explosives, and minecarts. Minecarts are optional, based on if "carts" is included after the command.
    usage: /<command> <carts>
  saconfig:
    description: Owner command - Manage superadmins.
    usage: /<command> <list | <add|delete> <username>>
  say:
    description: Broadcasts the given message as the console, includes sender name.
    usage: /<command> <message>
  setlevel:
    description: Sets your expierence level.
    usage: /<command> [level]
  setspawnworld:
    description: Superadmin Command - Set world spawnpoint.
    usage: /<command>
  ender:
    description: Goto the ender / "The End".
    usage: /<command>
  status:
    description: Show misc. server info.
    usage: /<command>
  stfu:
    description: Superadmin Command - Mutes a player with brute force.
    usage: /<command> <list | purge | <player>
  stop:
    description: Superadmin command - Kicks everyone and stops the server.
    usage: /<command>
  survival:
    description: Quickly change your own gamemode to survival, or define someone's username to change theirs.
    usage: /<command> [partialname]
  terminal:
    description: Execute a system command.
    usage: /<command> <syscmd>
  tfbanlist:
    description: Shows all banned player names. Superadmins may optionally use 'purge' to clear the list.
    usage: /<command> [purge]
  tfipbanlist:
    description: Shows all banned IPs. Superadmins may optionally use 'purge' to clear the list.
    usage: /<command> [purge]
  tossmob:
    description: Throw a mob in the direction you are facing when you left click with a stick.
    usage: /<command> <mobtype [speed] | off | list> 
  uall:
    description: Superadmin command - Undisguises all players
    usage: /<command>
  waterplace:
    description: Superadmin command - Enable/disable water placement.
    usage: /<command> <on | off>
  wildcard:
    description: Superadmin command - Run any command on all users, username placeholder = ?.
    usage: /<command> [fluff] ? [fluff] ?
#  wipeflatlands:
#    description: Console Command - Wipe the flatlands map.
#    usage: /<command>
  ziptool:
    description: Owner command - Zip and unzip files.
    usage: /<command> <zip <directory>> | <unzip <file>>
